openapi: "3.0.0"
info:
  title: Video Management API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload a video
      operationId: uploadVideo
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
      responses:
        '200':
          description: Video uploaded successfully
        '400':
          description: Bad request, unable to parse form
        '500':
          description: Internal server error during file processing

  /listvideos:
    get:
      summary: List uploaded videos
      operationId: listVideos
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
        - name: itemsPerPage
          in: query
          description: Number of items 
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of uploaded videos
        '500':
          description: Internal server error

  /deletevideo:
    delete:
      summary: Delete a video by ID
      operationId: deleteVideo
      parameters:
        - name: id
          in: query
          description: ID of the video to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Video deleted successfully
        '400':
          description: Bad request, missing video ID
        '500':
          description: Internal server error

  /videodetails:
    get:
      summary: Get details of a specific video
      operationId: getVideoDetails
      parameters:
        - name: id
          in: query
          description: ID of the video to retrieve details for
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Video details retrieved successfully
        '400':
          description: Bad request, missing video ID
        '404':
          description: Video not found
        '500':
          description: Internal server error
